name: Clear Actions caches

on:
  workflow_dispatch:

permissions: {}

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete all caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh cache delete --all
